typography_spectrum: 0.5
color:
  brandColors:
    - '#666666'
    - '#dc2a25'
    - '#101010'
    - '#ffffff'
    - '#9c9c9c'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8
analytics:
  google: null
  facebook: null
  twitter: null
name: EquesMedia
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: EquesMedia
description: Designer & Developer
purpose: []
